/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as WorkoutsCreateIndexRouteImport } from './routes/workouts/create/index'
import { Route as WorkoutsWorkoutIdIndexRouteImport } from './routes/workouts/$workoutId/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as WorkoutsWorkoutIdAddExercisesIndexRouteImport } from './routes/workouts/$workoutId/add-exercises/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsCreateIndexRoute = WorkoutsCreateIndexRouteImport.update({
  id: '/workouts/create/',
  path: '/workouts/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdIndexRoute = WorkoutsWorkoutIdIndexRouteImport.update({
  id: '/workouts/$workoutId/',
  path: '/workouts/$workoutId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdAddExercisesIndexRoute =
  WorkoutsWorkoutIdAddExercisesIndexRouteImport.update({
    id: '/workouts/$workoutId/add-exercises/',
    path: '/workouts/$workoutId/add-exercises/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdIndexRoute
  '/workouts/create': typeof WorkoutsCreateIndexRoute
  '/workouts/$workoutId/add-exercises': typeof WorkoutsWorkoutIdAddExercisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdIndexRoute
  '/workouts/create': typeof WorkoutsCreateIndexRoute
  '/workouts/$workoutId/add-exercises': typeof WorkoutsWorkoutIdAddExercisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/workouts/$workoutId/': typeof WorkoutsWorkoutIdIndexRoute
  '/workouts/create/': typeof WorkoutsCreateIndexRoute
  '/workouts/$workoutId/add-exercises/': typeof WorkoutsWorkoutIdAddExercisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workouts'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/workouts/$workoutId'
    | '/workouts/create'
    | '/workouts/$workoutId/add-exercises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workouts'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/workouts/$workoutId'
    | '/workouts/create'
    | '/workouts/$workoutId/add-exercises'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/workouts/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/workouts/$workoutId/'
    | '/workouts/create/'
    | '/workouts/$workoutId/add-exercises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  WorkoutsWorkoutIdIndexRoute: typeof WorkoutsWorkoutIdIndexRoute
  WorkoutsCreateIndexRoute: typeof WorkoutsCreateIndexRoute
  WorkoutsWorkoutIdAddExercisesIndexRoute: typeof WorkoutsWorkoutIdAddExercisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/create/': {
      id: '/workouts/create/'
      path: '/workouts/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof WorkoutsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId/': {
      id: '/workouts/$workoutId/'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId/add-exercises/': {
      id: '/workouts/$workoutId/add-exercises/'
      path: '/workouts/$workoutId/add-exercises'
      fullPath: '/workouts/$workoutId/add-exercises'
      preLoaderRoute: typeof WorkoutsWorkoutIdAddExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  WorkoutsWorkoutIdIndexRoute: WorkoutsWorkoutIdIndexRoute,
  WorkoutsCreateIndexRoute: WorkoutsCreateIndexRoute,
  WorkoutsWorkoutIdAddExercisesIndexRoute:
    WorkoutsWorkoutIdAddExercisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
