name: Build App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run linting
        run: pnpm run lint
        
      - name: Run type checking
        run: |
          pnpm --filter @fit-tracker/web typecheck
          pnpm --filter @fit-tracker/server typecheck
        
      - name: Build applications
        run: pnpm run build
        
      - name: Run tests
        run: |
          pnpm --filter @fit-tracker/server test
          pnpm --filter @fit-tracker/web test:run
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: |
            apps/web/dist/
            apps/server/dist/
            apps/server/drizzle.config.ts
            apps/server/src/env.ts
            apps/server/src/db/migrations/
            package.json
            pnpm-lock.yaml
            pnpm-workspace.yaml
            apps/*/package.json
            packages/*/package.json
          retention-days: 30
          
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Building Docker image for commit ${{ github.sha }}"
          docker build -t fit-tracker:${{ github.sha }} .
          docker save fit-tracker:${{ github.sha }} | gzip > fit-tracker-${{ github.sha }}.tar.gz
          
      - name: Upload Docker image artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: fit-tracker-${{ github.sha }}.tar.gz
          retention-days: 7